#!/bin/bash
#
# A script to toggle the screen brightness using file-based brightness settings.
#
# To install:
#
# sudo install 00-screen-brightness /etc/pm/sleep.d
# sudo install 00-screen-brightness /etc/pm/power.d
#

##
## POWER SAVE OFF
##
ac_power()
{
  # set AC brightness if enforced or higher than current one
  if [ "$enforce_brightness" == "true" ] || [ "$ac_brightness" -gt "$CURRENT_BRIGHTNESS" ]; then
    fc_set_brightness "$ac_brightness"
  fi
}

##
## POWER SAVE ON
##
battery_power()
{
  # set battery brightness if enforced or lower than current one
  if [ "$enforce_brightness" == "true" ] || [ "$battery_brightness" -lt "$CURRENT_BRIGHTNESS" ]; then
    fc_set_brightness "$battery_brightness"
  fi
}

# Gets the current screen brightness.
#
# Returns: (int) current screen brightness in percent
fc_get_brightness ()
{
  # get current and maximum absolute brightness
  local CURRENT_BRIGHTNESS=$( brightnessctl g )
  local MAX_BRIGHTNESS=$( brightnessctl m )
  # calculate relative brightness
  echo $(( CURRENT_BRIGHTNESS * 100 / MAX_BRIGHTNESS ))
}

# Sets the desired screen brightness.
#
# Params:
# 1. (int) desired screen brightness in percent
fc_set_brightness ()
{
  brightnessctl s "$1%"
}

if [ "${BASH_SOURCE[0]}" == "${0}" ]; then
  # defaults
  battery_brightness=65
  ac_brightness=100
  enforce_brightness=false

  # get primary user
  USER=$( who | head -n 1 | cut -d ' ' -f1 )
  # load user configuration, if existing
  CFGFILE="/home/$USER/.config/xpower/brightness"
  if [ -f "$CFGFILE" ]; then
    source "$CFGFILE"
  fi

  # get current brightness
  CURRENT_BRIGHTNESS=$( fc_get_brightness )

  ##
  ## APPLY SETTINGS
  ##
  case "$1" in
    false) ac_power ;;
    true) battery_power ;;
  esac
  exit 0
fi
